const people = [
	{
		id: "1",
		customer: "Jane Cooper",
		company: "Microsof",
		phone: "(225) 555-0118",
		email: "jane@microsof.com",
		country: "United States",
		status: "Active",
	},
	{
		id: "2",
		customer: "Floyd miles",
		company: "Yahoo",
		phone: "(205) 555-0100",
		email: "floyd@yahoo.com",
		country: "Kiribati",
		status: "Inactive",
	},
	{
		id: "3",
		customer: "Ronald Richards",
		company: "Adobe",
		phone: "(302) 555-0107",
		email: "ronald@adobe.com",
		country: "Israel",
		status: "Inactive",
	},
	{
		id: "4",
		customer: "Marvin McKinney",
		company: "Tesla",
		phone: "(252) 555-0126",
		email: "marvin@tesla.com",
		country: "Iran",
		status: "Active",
	},
	{
		id: "5",
		customer: "Jerome Bell",
		company: "Google",
		phone: "(629) 555-0129",
		email: "jerome@google.com",
		country: "Reunion",
		status: "Active",
	},
	{
		id: "6",
		customer: "Kathryn Murphy",
		company: "Microsof",
		phone: "(406) 555-0120",
		email: "kathryn@microsof.com",
		country: "Curacao",
		status: "Active",
	},
	{
		id: "7",
		customer: "Jacob Jones",
		company: "Yahoo",
		phone: "(208) 555-0112",
		email: "jacob@yahoo.com",
		country: "Brazil",
		status: "Active",
	},
	{
		id: "8",
		customer: "Kristin Watson",
		company: "Facebook",
		phone: "(704) 555-0127",
		email: "kristin@facebook.com",
		country: "Aland Islands",
		status: "Inactive",
	},
]

export default people
